# Generated by Django 5.2.8 on 2026-03-11 01:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("parametric_generator", "0002_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="project",
            name="project_image",
            field=models.ImageField(
                blank=True,
                help_text="Optional cover image for the project",
                null=True,
                upload_to="project_images/",
            ),
        ),
        migrations.AddField(
            model_name="site",
            name="site_image",
            field=models.ImageField(
                blank=True,
                help_text="Optional image/thumbnail for this site",
                null=True,
                upload_to="site_images/",
            ),
        ),
    ]
