# Generated by Django 5.2.8 on 2026-03-19 17:16

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parametric_generator', '0004_rename_asset_to_element'),
    ]

    operations = [
        migrations.CreateModel(
            name='Facility',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique facility identifier (UUID)', primary_key=True, serialize=False)),
                ('name', models.CharField(help_text='Facility name', max_length=255)),
                ('facility_type', models.CharField(choices=[('BUILDING', 'Building'), ('INFRA_ROAD', 'Road'), ('INFRA_RAILWAY', 'Railway'), ('INFRA_BRIDGE', 'Bridge'), ('INFRA_TUNNEL', 'Tunnel'), ('INFRA_MARINE', 'Marine Facility'), ('INDUSTRIAL_FACTORY', 'Factory'), ('INDUSTRIAL_PLANT', 'Process Plant'), ('INFRA_DISTRIBUTION', 'Distribution System'), ('SITE', 'Site / Land Project'), ('OTHER', 'Other / Custom')], help_text='Facility type (Building, Road, Bridge, etc.)', max_length=50)),
                ('description', models.TextField(blank=True, null=True)),
                ('properties', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.RenameIndex(
            model_name='element',
            new_name='parametric__site_id_df2d3b_idx',
            old_name='parametric__site_id_005f9c_idx',
        ),
        migrations.RenameIndex(
            model_name='element',
            new_name='parametric__spatial_60ee9f_idx',
            old_name='parametric__spatial_dd6814_idx',
        ),
        migrations.AddField(
            model_name='facility',
            name='project',
            field=models.ForeignKey(help_text='Project this facility belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='facilities', to='parametric_generator.project'),
        ),
        migrations.AddField(
            model_name='facility',
            name='site',
            field=models.ForeignKey(help_text='Site that contains this facility', on_delete=django.db.models.deletion.CASCADE, related_name='facilities', to='parametric_generator.site'),
        ),
        migrations.AddIndex(
            model_name='facility',
            index=models.Index(fields=['project', 'facility_type'], name='parametric__project_1c2c4f_idx'),
        ),
        migrations.AddIndex(
            model_name='facility',
            index=models.Index(fields=['site'], name='parametric__site_id_11cea1_idx'),
        ),
    ]
