# Generated by Django 5.2.8 on 2026-03-19 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parametric_generator', '0005_facility_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='facility',
            name='facility_image',
            field=models.ImageField(blank=True, help_text='Optional image/thumbnail for this facility', null=True, upload_to='facility_images/'),
        ),
        migrations.AlterField(
            model_name='project',
            name='project_type',
            field=models.CharField(blank=True, choices=[('BUILDING', 'Building'), ('INFRA_ROAD', 'Road'), ('INFRA_RAILWAY', 'Railway'), ('INFRA_BRIDGE', 'Bridge'), ('INFRA_TUNNEL', 'Tunnel'), ('INFRA_MARINE', 'Marine Facility'), ('INDUSTRIAL_FACTORY', 'Factory'), ('INDUSTRIAL_PLANT', 'Process Plant'), ('INFRA_DISTRIBUTION', 'Distribution System'), ('SITE', 'Site / Land Project'), ('OTHER', 'Other / Custom')], help_text='(Deprecated) Project-level type; facilities carry the active type.', max_length=50, null=True),
        ),
    ]
