# Generated by Django 5.2.8 on 2026-03-19 17:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('parametric_generator', '0006_facility_facility_image_alter_project_project_type'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='project',
            name='parametric__project_f830af_idx',
        ),
        migrations.RemoveField(
            model_name='project',
            name='project_type',
        ),
    ]
