# Generated by Django 5.2.8 on 2026-03-19 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parametric_generator', '0007_remove_project_parametric__project_f830af_idx_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='site',
            name='project_type',
        ),
        migrations.AlterField(
            model_name='site',
            name='type_metadata',
            field=models.JSONField(blank=True, default=dict, help_text='Type-specific site details (if any).'),
        ),
    ]
