# Generated by Django 5.2.8 on 2026-03-29 23:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parametric_generator', '0009_material'),
    ]

    operations = [
        migrations.AddField(
            model_name='element',
            name='facility',
            field=models.ForeignKey(blank=True, help_text='Facility this element belongs to', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='elements', to='parametric_generator.facility'),
        ),
        migrations.AlterField(
            model_name='element',
            name='properties',
            field=models.JSONField(blank=True, default=dict, help_text='Type-specific properties (dimensions, specs)'),
        ),
        migrations.AlterField(
            model_name='element',
            name='site',
            field=models.ForeignKey(help_text='Site for quick filtering and context', on_delete=django.db.models.deletion.CASCADE, related_name='elements', to='parametric_generator.site'),
        ),
        migrations.AlterField(
            model_name='element',
            name='spatial_structure',
            field=models.ForeignKey(help_text='Spatial structure this element belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='elements', to='parametric_generator.spatialstructure'),
        ),
    ]
