# Generated by Django 5.2.8 on 2026-03-29 23:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parametric_generator', '0010_element_facility_alter_element_properties_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='element',
            name='asset_type',
            field=models.CharField(choices=[('wall', 'Wall'), ('beam', 'Beam'), ('slab', 'Slab'), ('column', 'Column'), ('foundation', 'Foundation'), ('door', 'Door'), ('window', 'Window'), ('roof', 'Roof'), ('stairs', 'Stairs'), ('ramp', 'Ramp'), ('shear_wall', 'Shear Wall'), ('pipe', 'Pipe'), ('duct', 'Duct'), ('cable', 'Cable'), ('fitting', 'Fitting'), ('equipment', 'Equipment'), ('sensor', 'Sensor'), ('beam_span', 'Beam Span'), ('girder', 'Girder'), ('pier', 'Pier'), ('abutment', 'Abutment'), ('bearing', 'Bearing'), ('expansion_joint', 'Expansion Joint'), ('bridge_railing', 'Bridge Railing'), ('bridge_deck', 'Bridge Deck Element'), ('pavement', 'Pavement'), ('curb', 'Curb'), ('marking', 'Road Marking'), ('sign', 'Road Sign'), ('light', 'Street Light'), ('manhole', 'Manhole'), ('storm_drain', 'Storm Drain'), ('alignment', 'Alignment'), ('kerb', 'Kerb'), ('other', 'Other')], help_text='Type of asset (Wall, Beam, Pipe, etc.)', max_length=50),
        ),
        migrations.AlterField(
            model_name='facility',
            name='facility_type',
            field=models.CharField(choices=[('IFC_BUILDING', 'IFC Building'), ('IFC_ROAD', 'IFC Road'), ('IFC_RAILWAY', 'IFC Railway'), ('IFC_BRIDGE', 'IFC Bridge'), ('IFC_TUNNEL', 'IFC Tunnel'), ('IFC_MARINE', 'IFC Marine Facility'), ('IFC_FACTORY', 'IFC Factory'), ('IFC_PROCESS_PLANT', 'IFC Process Plant'), ('IFC_DISTRIBUTION_SYSTEM', 'IFC Distribution System'), ('IFC_SITE', 'IFC Site'), ('IFC_OTHER', 'IFC Other')], help_text='Facility type (Building, Road, Bridge, etc.)', max_length=50),
        ),
    ]
